### ISSUE TITLE
FASTA files with .fas suffix are not recognized

### ISSUE THREAD

**Issue by kjolley** [ntopaz/characterize_neisseria_capsule#1]
It should be either made clear that FASTA files need to have either .fasta or .fna suffixes, or preferably, the software would load files with any name.

**Comment by ntopaz** [comment]
Thank you for pointing this out. I have added the .fas file extension, documented the required extensions  and improved the way that the files get tracked throughout the software. 

In a future version I will update the software to handle each file appropriately regardless of extension.
