### ISSUE TITLE
ImportError Bio.Alphabet

### ISSUE THREAD

**Issue by davidmaimoun** [ntopaz/characterize_neisseria_capsule#2]
Hi Nadav
Thank you for the tool!
I get this error when I run the main script: 'ImportError: Bio.Alphabet has been removed from Biopython.'
Do you have a updated script?

Thank you

**Comment by ntopaz** [comment]
Hello! This has been fixed. Please go ahead and pull down the latest version of the script from the master branch. Thanks for reporting the issue!

**Comment by davidmaimoun** [comment]
Tank you very much
